# frozen_string_literal: true

Section.create(code: 'podvoh',        name: 'Подводная охота')
Category.create(code: 'pnevmat',      name: 'Пневматические ружья')
Category.create(code: 'video',        name: 'Видеокамеры')
Category.create(code: 'flashlights',  name: 'Фонари, аккумуляторы')
Category.create(code: 'mask',         name: 'Маски')
Category.create(code: 'tube',         name: 'Трубки')
Category.create(code: 'knives',       name: 'Ножи')
Category.create(code: 'footpocket',   name: 'Калоши')
Category.create(code: 'fins',         name: 'Ласты')
Category.create(code: 'fin_blades',   name: 'Лопасти')
Category.create(code: 'belts',        name: 'Ремни, разгрузки')
Category.create(code: 'bags',         name: 'Сумки')
Category.create(code: 'buoys',        name: 'Буи, плотики')
Category.create(code: 'speargun',     name: 'Арбалеты')
Category.create(code: 'wetsuits',     name: 'Гидрокостюмы')
Category.create(code: 'socks',        name: 'Носки')
Category.create(code: 'belt_weights', name: '')
Category.create(code: 'reels',        name: 'Катушки')
Category.create(code: 'shafts',       name: 'Гарпуны, пули')
Category.create(code: 'hooks',        name: 'Куканы')
Category.create(code: 'watch',        name: 'Часы')
Category.create(code: 'gloves',       name: 'Перчатки')
Category.create(code: 'lines',        name: 'Линь, буй-линь')
Category.create(code: 'accessories',  name: 'Аксесуары')
Category.create(code: 'parts',        name: 'Запчасти')
Manufacturer.create(code: 'kayuk',        name: 'Каюк',        country: 'by',     www: '',     phone: '',    email: '',    address: '')
Manufacturer.create(code: 'c4',           name: 'C4',          country: 'it',     www: '',     phone: '',    email: '',    address: '')
Manufacturer.create(code: 'beuchat',      name: 'Beuchat',     country: '',     www: '',     phone: '',    email: '',    address: '')
Manufacturer.create(code: 'salvimar',     name: 'Salvimar',    country: '',     www: '',     phone: '',    email: '',    address: '')
Manufacturer.create(code: 'scorpena',     name: 'Scorpena',    country: '',     www: '',     phone: '',    email: '',    address: '')
Manufacturer.create(code: 'pelengas',     name: 'Pelengas',    country: '',     www: '',     phone: '',    email: '',    address: '')
# Manufacturer.create(code: '',      name: '',    country: '',     www: '',     phone: '',    email: '',    address: '')
# Manufacturer.create(code: '',      name: '',    country: '',     www: '',     phone: '',    email: '',    address: '')
